### ISSUE TITLE
Create evercam compare does not complete (Processing....)

### ISSUE THREAD

**Issue by JaviCT** [evercam/evercam-server#1022]
![image](https://user-images.githubusercontent.com/19703794/48138503-5abe5a00-e29c-11e8-818f-0cf2b4dca423.png)

@azharmalik3  @ijunaid8989

**Comment by ijunaid8989** [comment]
```
** (File.Error) could not read file "/storage/compa-mrnxxhu/compa-mrnxxhu.mp4": no such file or directory
    (elixir) lib/file.ex:319: File.read!/1
    (evercam_media) lib/evercam_media/timelapse_recording/s3.ex:44: anonymous fn/1 in EvercamMedia.TimelapseRecording.S3.do_save_multiple/1
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<1.127147751/1 in EvercamMedia.TimelapseRecording.S3.do_save_multiple/1>
```

**Comment by marcoherbst** [comment]
@azharmalik3 I think you've fixed this now, right?

**Comment by azharmalik3** [comment]
Yes. I am closing this.
