### ISSUE TITLE
Fix test warnings when making queries in the background

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-server#275]
Right now camera deletion queries run in the background, which is making the camera deletion test to throw this error:

```
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.2125.0>.

When using ownership, you must manage connections in one
of the three ways:

  * By explicitly checking out a connection
  * By explicitly allowing a spawned process
  * By running the pool in shared mode

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

See Ecto.Adapters.SQL.Sandbox docs for more information.
    (db_connection) lib/db_connection.ex:722: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:623: DBConnection.run/3
    (db_connection) lib/db_connection.ex:464: DBConnection.prepare_execute/4
    (ecto) lib/ecto/adapters/sql.ex:228: Ecto.Adapters.SQL.sql_call/6
    (ecto) lib/ecto/adapters/sql.ex:400: Ecto.Adapters.SQL.execute_and_cache/7
    (evercam_media) web/controllers/camera_controller.ex:375: EvercamMedia.CameraController.delete_snapshot_worker/1
```

I've tagged the test to be skipped in https://github.com/evercam/evercam-media/commit/98cf33ccc257b8c297c80ee61a6a88fffedee32e.

**Comment by azharmalik3** [comment]
I have verified this issue and it's already fixed.
