### ISSUE TITLE
When enabling Motion Detection some cameras stop working

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#362]
Some cameras stop rendering jpeg image after some time.

Like this camera: https://dash.evercam.io/v1/cameras/hikvis-ext/live

**Comment by azharmalik3** [comment]
I have tested broken live view deeply and viewed somologic logs. There are a lot of crash issues of the worker. Also noticed that recording stopped when crash worker.

```
=CRASH REPORT==== 8-Aug-2016::04:09:53 ===
  crasher:
    initial call: Elixir.EvercamMedia.Snapshot.Worker:init/1
    pid: <0.16363.160>
    registered_name: 'bennett-dorset'
    exception exit: {system_limit,
                        [{erlang,spawn,
                         {erlang,spawn,1,[]},
                         {'Elixir.EvercamMedia.Snapshot.Worker',handle_cast,
                             2, [{file,"lib/evercam_media/snapshot/worker.ex"}, {line,126}]},
      in function  gen_server:terminate/7 (gen_server.erl, line 826)
    ancestors: ['Elixir.EvercamMedia.Snapshot.WorkerSupervisor',
                  'Elixir.EvercamMedia.Supervisor',<0.205.0>]
  neighbours:
    neighbour: [{pid,<0.16365.160>},
                  {registered_name,[]},
                  {initial_call,
                  {current_function,{gen_server,loop,6}},
                  {ancestors,
                      ['bennett-dorset',
                       'Elixir.EvercamMedia.Snapshot.WorkerSupervisor',
                       'Elixir.EvercamMedia.Supervisor',<0.205.0>]},
=SUPERVISOR REPORT==== 8-Aug-2016::04:09:53 ===
     Supervisor: {local,'Elixir.EvercamMedia.Snapshot.WorkerSupervisor'}
     Context:    child_terminated
     Reason:     {system_limit,
                     [{erlang,spawn,
                          [erlang,apply,
                      {erlang,spawn,1,[]},
                      {'Elixir.EvercamMedia.Snapshot.Worker',handle_cast,2,
                          [{file,"lib/evercam_media/snapshot/worker.ex"},
                           {line,126}]},
     Offender:   [{pid,<0.16363.160>},
                  {id,'Elixir.EvercamMedia.Snapshot.Worker'},
                  {mfargs,
                      {'Elixir.EvercamMedia.Snapshot.Worker',start_link,
                          [#{config => #{auth => <<"admin:Mehcam4Mehcam">>,
                               camera_exid => <<"bennett-dorset">>,
                               camera_id => 10363,
                               initial_sleep => 1000,
                               schedule => #{<<"Friday">> => [<<"00:00-23:59">>],
                                 <<"Monday">> => [<<"00:00-23:59">>],
                                 <<"Saturday">> => [<<"00:00-23:59">>],
                                 <<"Sunday">> => [<<"00:00-23:59">>],
                                 <<"Thursday">> => [<<"00:00-23:59">>],
                                 <<"Tuesday">> => [<<"00:00-23:59">>],
                                 <<"Wednesday">> => [<<"00:00-23:59">>]},
                               sleep => 1000,
                               timezone => <<"Europe/Dublin">>,
                               url => <<"http://89.100.74.79:8100/ISAPI/Streaming/channels/101/picture">>,
                               vendor_exid => <<"hikvision">>},
                             event_handlers => ['Elixir.EvercamMedia.Snapshot.BroadcastHandler',
                              'Elixir.EvercamMedia.Snapshot.DBHandler',
                              'Elixir.EvercamMedia.Snapshot.PollHandler',
                              'Elixir.EvercamMedia.Snapshot.StorageHandler'],
                             name => 'bennett-dorset'}]}},
                  {restart_type,permanent},
                  {shutdown,5000},
                  {child_type,worker}]
2016-08-08 04:09:53.121 [error] Too many processes
2016-08-08 04:09:53.121 [error] GenEvent handler EvercamMedia.Snapshot.StorageHandler installed in #PID<0.15892.128> terminating
** (SystemLimitError) a system limit has been reached
    :erlang.spawn(:erlang, :apply, [#Function<0.48354199/0 in EvercamMedia.Snapshot.StorageHandler.handle_event/2>, []])
    :erlang.spawn/1
    (evercam_media) lib/evercam_media/snapshot/storage_handler.ex:12: EvercamMedia.Snapshot.StorageHandler.handle_event/2
    (elixir) lib/gen_event.ex:1104: GenEvent.do_handler/3
    (elixir) lib/gen_event.ex:945: GenEvent.server_update/5
    (elixir) lib/gen_event.ex:930: GenEvent.server_notify/7
    (elixir) lib/gen_event.ex:903: GenEvent.server_event/4
    (elixir) lib/gen_event.ex:709: GenEvent.handle_msg/5
```

Restart application solves this issues but only for 1 hour. After 1-hour worker again starts crash.

After that, we just reverted motion detection work and deployed media. Without motion detection  code media stop worker crashes frequently but worker still crashes after a long time (not sure how much time, last time noticed that it crashed after 2 days over the weekend).

**Comment by azharmalik3** [comment]
Live view stopped working after some time because there are too many processes running on the server which terminate the processes when it reaches the maximum system limits.

Application failed to shutdown worker in case of failed snapshot and it starts another camera process which causes system reached to maximum limits.

Also, it stopped snapshot recordings.

Another issue occurred when system try to update camera status. We are using 1 sec timer to update camera status which timeout before the complete task. It causes multiple offline/online logs and stale camera struct.

In reference to Google Group Question. I have no idea about the actual issue being discussed in google QA but after disabling MD work we are also restarting evercam-media after 2 3 hours for last 2 weeks.

The live is being stopped and effecting recordings as well and most of the time the error occurred in logs is “Error Gist” the line on which this error occurs. Moreover when a camera’s status is ONLINE apparently, but it's not recording anything then after changing the CR settings of the camera, make the camera running and start recording again, as its process starts again when CR settings updated/changed.

maybe there was no pattern,?

Maybe there is no pattern of affected cameras, BUT logs give error pattern, first the above gist error came across and it came multiple times, + Device busy + etc issues came accross, resulting Stopped Live View And Recording.

What we studied so far and considered the focal point to discuss is
