### ISSUE TITLE
Error in evercam server logs

### ISSUE THREAD

**Issue by ijunaid8088** [evercam/evercam-server#663]
```
2017-03-09 06:59:18.872 [error] %UndefinedFunctionError{arity: 2, function: :fetch, module: RuntimeError, reason: "RuntimeError does not implement the Access behaviour"}
2017-03-09 06:59:18.872 [error]     (elixir) RuntimeError.fetch(%RuntimeError{message: "No string found"}, :response)
    (elixir) lib/access.ex:148: Access.fetch/2
    (elixir) lib/access.ex:179: Access.get/3
    (evercam_media) lib/evercam_media/snapshot/error.ex:108: EvercamMedia.Snapshot.Error.handle/4
    (evercam_media) lib/evercam_media/snapshot/db_handler.ex:35: EvercamMedia.Snapshot.DBHandler.handle_event/2
    (elixir) lib/gen_event.ex:1104: GenEvent.do_handler/3
    (elixir) lib/gen_event.ex:945: GenEvent.server_update/5
    (elixir) lib/gen_event.ex:930: GenEvent.server_notify/7
```

**Comment by marcoherbst** [comment]
@ijunaid8088  some context please. Is this important? Milestone? Priority?

**Comment by ijunaid8088** [comment]
Not important, Just a formal error coming from a camera. I have added to March Milestone.

**Comment by marcoherbst** [comment]
@ijunaid8088 this issue needs some explanation.

**Comment by ijunaid8088** [comment]
Yeah sure.

As When camera worker is getting a snapshot from the camera, instead of an image the coming response is a string, which we consider as a soft error in the category of `not_a_jpeg`.

**Comment by ijunaid8088** [comment]
Its done.
