### ISSUE TITLE
Application terminated on '/v1/cameras/avolo-secto/ptz/presets'

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-server#891]
```
Request: GET /v1/cameras/avolo-secto/ptz/presets?api_id=***&api_key=*****
** (exit) an exception was raised:
    ** (BadMapError) expected a map, got: :ok
        (elixir) lib/map.ex:424: Map.get(:ok, "Preset", nil)
        (evercam_media) lib/evercam_media/onvif/onvif_ptz.ex:15: EvercamMedia.ONVIFPTZ.get_presets/2
        (evercam_media) lib/evercam_media_web/controllers/onvifptz_controller.ex:19: EvercamMediaWeb.ONVIFPTZController.presets/2
        (evercam_media) lib/evercam_media_web/controllers/onvifptz_controller.ex:1: EvercamMediaWeb.ONVIFPTZController.action/2
        (evercam_media) lib/evercam_media_web/controllers/onvifptz_controller.ex:1: EvercamMediaWeb.ONVIFPTZController.phoenix_controller_pipeline/2
        (evercam_media) lib/evercam_media_web/endpoint.ex:1: EvercamMediaWeb.Endpoint.instrument/4
```

**Comment by marcoherbst** [comment]
@ijunaid8989 this gets assigned to you unless you think it is better with @azharmalik3 . 

Well done for spotting it.

**Comment by ijunaid8989** [comment]
its done.
