### ISSUE TITLE
General exceptions should be handled more beautifully

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-server#967]
```
2018-08-02 07:57:37.731 [info] Started poller evercam_bot
warning: An empty bot_name env will make '/anycommand@' valid
  (evercam_media) lib/evercam_media/evercam_bot/telegram_supervisor.ex:44: EvercamMedia.EvercamBot.TelegramSupervisor.start_matcher/0
  (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
  (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

```
2018-08-02 08:07:31.627 request_id=lth1506mfio2m1l3kj91uf2nk2psrlsb [error] %RuntimeError{message: "Invalid RTSP port to request the video stream"}
2018-08-02 08:07:31.627 request_id=lth1506mfio2m1l3kj91uf2nk2psrlsb [error]     (evercam_media) lib/evercam_media_web/controllers/stream_controller.ex:68: EvercamMediaWeb.StreamController.check_port/1
    (evercam_media) lib/evercam_media_web/controllers/stream_controller.ex:53: EvercamMediaWeb.StreamController.request_stream/4
    (evercam_media) lib/evercam_media_web/controllers/stream_controller.ex:12: EvercamMediaWeb.StreamController.hls/2
    (evercam_media) lib/evercam_media_web/controllers/stream_controller.ex:1: EvercamMediaWeb.StreamController.action/2
    (evercam_media) lib/evercam_media_web/controllers/stream_controller.ex:1: EvercamMediaWeb.StreamController.phoenix_controller_pipeline/2
    (evercam_media) lib/evercam_media_web/endpoint.ex:1: EvercamMediaWeb.Endpoint.instrument/4
    (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
    (evercam_media) lib/evercam_media_web/endpoint.ex:1: EvercamMediaWeb.Endpoint.plug_builder_call/2
```
All the exception coming from `Request: GET /v1/cameras/{camera_exid}/nvr/{video/recordings/days/hours}`

**Comment by ijunaid8989** [comment]
its done.
